---
root: true

env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2017

plugins:
- node
- import
- prettier

extends:
- plugin:node/recommended
- plugin:import/errors
- plugin:import/warnings

rules:
  prettier/prettier: error
